# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NativeModuleSample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Google-Mobile-Ads-SDK'

  # Pods for NativeModuleSample

  # target 'NativeModuleSample-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  target 'NativeModuleSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'NativeModuleSampleDev' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Google-Mobile-Ads-SDK'

  # Pods for NativeModuleSample

  # target 'NativeModuleSample-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

end

target 'NativeModuleSample-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NativeModuleSample-tvOS

  target 'NativeModuleSample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
